In [3]:
'''
@author: Mahmoud Mohammadi
Data Set : https://www.kaggle.com/cityofLA/city-payroll-data 

'''    

import csv
import collections as c
import math 
import operator
import numpy as np
import pandas as pd
import collections as c
import scipy.spatial.distance as sc
import copy
import datetime

import pickle

import re

In [4]:
with open('data/LA_normal_5_5.pickle', 'rb') as handle:
    df_loaded = pickle.load(handle)

In [57]:
df_fake.shape

(64, 5, 5, 1)

In [16]:
fake.shape

(64, 5, 5)

In [7]:
df_loaded.shape

(285008, 5, 5)

In [74]:
real= np.array(df_loaded[:64,:,:])

In [49]:
real.shape

(64, 5, 5)

In [60]:
std_real =np.std(real, axis=0)

In [87]:
with open('samples/train_00_0499.pickle', 'rb') as handle:
    df_fake = pickle.load(handle)

fake = np.array(df_fake[:,:,:,0])

std_fake =np.std(fake, axis=0)

In [84]:
np.isclose(std_real, std_fake, rtol=0, atol=1e-02) # rtol*abs(x)+atol > x -y :  0699

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [86]:
np.isclose(std_real, std_fake, rtol=0, atol=1e-02) # rtol*abs(x)+atol > x -y :  0599

array([[False, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [88]:
np.isclose(std_real, std_fake, rtol=0, atol=1e-02) # rtol*abs(x)+atol > x -y :  0499

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [80]:
np.isclose(std_real, std_fake, rtol=0, atol=1e-02) # rtol*abs(x)+atol > x -y :  0399

array([[False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [78]:
np.isclose(std_real, std_fake, rtol=0, atol=1e-02) # rtol*abs(x)+atol > x -y :  0299

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [76]:
np.isclose(std_real, std_fake, rtol=0, atol=1e-02) # rtol*abs(x)+atol > x -y :  0199

array([[False, False,  True, False, False],
       [ True,  True, False, False, False],
       [False, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [82]:
np.isclose(std_real, std_fake, rtol=0, atol=1e-02) # rtol*abs(x)+atol > x -y :  0099

array([[False, False,  True,  True, False],
       [False, False,  True, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [25]:
np.allclose([1e10,1e-8], [1e10,1e-9], rtol=0, atol=1e-09)

False