In [4]:
'''
@author: Mahmoud Mohammadi
Data Set : http://archive.ics.uci.edu/ml/datasets/Nomao

'''    

import csv
import collections as c
import math 
import operator
import numpy as np
import pandas as pd
import collections as c
import scipy.spatial.distance as sc
import copy
import datetime

import re


In [6]:
basePath =""
dataset ="Nomao"
dataFile = basePath + "Nomao.data.csv"

col_names = []
for i in range(1,121):
    col_names.append('f'+ str(i))



In [7]:
df = pd.read_csv(dataFile, header =None,names= col_names, low_memory=False)

df.head()

f1   f2    f3        f4        f5        f6        f7 f8 f9 f10 ...   \
0  0#1  1.0  1.00  1.000000  1.000000  1.000000  1.000000  s  s   ? ...    
1  0#2  1.0  0.75  0.857143  0.857143  0.894737  0.947368  s  n   ? ...    
2  0#3  1.0  1.00  1.000000  1.000000  1.000000  1.000000  s  s   ? ...    
3  4#5  1.0  0.75  0.857143  0.857143  0.842105  0.833333  s  n   1 ...    
4  6#7  0.0  0.00  0.250000  0.000000  0.250000  0.000000  n  n   ? ...    

             f111            f112 f113            f114            f115  \
0            0.75             0.5    n  0.999953002209  0.777777777778   
1             0.5  0.307692319155    n  0.999982921892  0.538461538462   
2  0.666666666667  0.461538463831    n  0.999992600055             0.8   
3             0.5  0.285714298487    n  0.998604948886  0.555555555556   
4               ?               ?    m               ?               ?   

             f116 f117            f118            f119 f120  
0  0.461538463831    n             1.0  0.999999996702    1  
1          0.4375    n             1.0  0.999999962459    1  
2  0.666666686535    n             1.0  0.999999999653    1  
3  0.384615391493    n  0.999999947284  0.999994124065    1  
4               ?    m             1.0               ?    1  

[5 rows x 120 columns]

In [11]:
selected_columns = ['f2','f3', 'f4', 'f5', 'f6', 'f7',
 'f10', 'f11', 'f12', 'f13', 'f14', 'f15',
 'f18', 'f19', 'f20', 'f21', 'f22', 'f23',
 'f26', 'f27', 'f28', 'f29', 'f30', 'f31',
 'f34', 'f35', 'f36', 'f37', 'f38', 'f39',
 'f42', 'f43', 'f44', 'f45', 'f46', 'f47',
 'f50', 'f51', 'f52', 'f53', 'f54', 'f55',
 'f58', 'f59', 'f60', 'f61', 'f62', 'f63',
 'f66', 'f67', 'f68', 'f69', 'f70', 'f71',
 'f74', 'f75', 'f76', 'f77', 'f78', 'f79',
 'f82', 'f83', 'f84', 'f85', 'f86', 'f87',
 'f90', 'f91', 'f92',
 'f94', 'f95', 'f96',
 'f98', 'f99', 'f100',
 'f102', 'f103', 'f104',
 'f106', 'f107', 'f108',
 ]
len(selected_columns)

81

In [36]:
# Selecting 24 columns having numeric data
df = df[selected_columns]
df.head()

f2    f3        f4        f5        f6        f7 f10 f11 f12 f13  \
0  1.0  1.00  1.000000  1.000000  1.000000  1.000000   ?   ?   ?   ?   
1  1.0  0.75  0.857143  0.857143  0.894737  0.947368   ?   ?   ?   ?   
2  1.0  1.00  1.000000  1.000000  1.000000  1.000000   ?   ?   ?   ?   
3  1.0  0.75  0.857143  0.857143  0.842105  0.833333   1   1   1   1   
4  0.0  0.00  0.250000  0.000000  0.250000  0.000000   ?   ?   ?   ?   

       ...       f96  f98  f99 f100            f102            f103  \
0      ...         ?  1.0  1.0  1.0             1.0             1.0   
1      ...         ?  1.0  1.0  1.0             1.0             1.0   
2      ...         ?  1.0  1.0  1.0             1.0             1.0   
3      ...         ?  1.0  1.0  1.0  0.999773651245  0.555555555556   
4      ...         ?    ?    ?    ?             1.0             1.0   

             f104            f106 f107           f108  
0             1.0             1.0  1.0            1.0  
1             1.0             1.0  1.0            1.0  
2             1.0             1.0  1.0            1.0  
3  0.333333343267  0.999961801459  0.5  0.29411765933  
4             1.0             1.0  1.0            1.0  

[5 rows x 81 columns]

In [14]:
#Finding columns having null vlaues  and replacing them with 0.0
#df2 = df.copy()
df.fillna(-1. , inplace= True)

In [37]:
# Replacing non numeric characters such as $ or E in cell values
import re
theregex = re.compile(r'[^\d.]+')

df = df.astype('str').applymap(lambda x: re.sub(r'[^\d.]+', '0', x))       

In [38]:
df = df.replace(r'\s+','0',regex=True)

In [40]:
# Changing all columns' types to float
df = df.astype('float')

In [53]:
#df2.drop('Label', axis=1, inplace=True)

In [42]:
df.head()

f2    f3        f4        f5        f6        f7  f10  f11  f12  f13  \
0  1.0  1.00  1.000000  1.000000  1.000000  1.000000  0.0  0.0  0.0  0.0   
1  1.0  0.75  0.857143  0.857143  0.894737  0.947368  0.0  0.0  0.0  0.0   
2  1.0  1.00  1.000000  1.000000  1.000000  1.000000  0.0  0.0  0.0  0.0   
3  1.0  0.75  0.857143  0.857143  0.842105  0.833333  1.0  1.0  1.0  1.0   
4  0.0  0.00  0.250000  0.000000  0.250000  0.000000  0.0  0.0  0.0  0.0   

     ...     f96  f98  f99  f100      f102      f103      f104      f106  \
0    ...     0.0  1.0  1.0   1.0  1.000000  1.000000  1.000000  1.000000   
1    ...     0.0  1.0  1.0   1.0  1.000000  1.000000  1.000000  1.000000   
2    ...     0.0  1.0  1.0   1.0  1.000000  1.000000  1.000000  1.000000   
3    ...     0.0  1.0  1.0   1.0  0.999774  0.555556  0.333333  0.999962   
4    ...     0.0  0.0  0.0   0.0  1.000000  1.000000  1.000000  1.000000   

   f107      f108  
0   1.0  1.000000  
1   1.0  1.000000  
2   1.0  1.000000  
3   0.5  0.294118  
4   1.0  1.000000  

[5 rows x 81 columns]

In [43]:
# Saving cleaned DataFrame for later use
df.to_pickle(basePath + dataset + "_cleaned.pickle")

In [44]:
# min_max is an array containing the Min and Max of each column in every row. 
# min_max[1,0] = Min(Col[1]) , min_max[1,1] = Max(Col[1]), min_max[2,0] = Min(Col[2]) , min_max[2,1] = Max(Col[2]) , ....

col_min = [ min(df[col]) for col in df.columns ]
col_max = [ max(df[col]) for col in df.columns ]
min_max= np.array([ (x,y) for x,y in zip(col_min, col_max)])


import csv
# Saving Min and Max of each Dataframe column in a CSV file: [Min Col 0, Max Col 0],...

with open(basePath + dataset + "_minmax.csv", 'w') as myfile:
    wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
    wr.writerow(min_max)



In [45]:
# Column-wise Normalizing of raw data in range of -1,1
from sklearn import preprocessing


min_max_scaler = preprocessing.MinMaxScaler(feature_range=(-1 , 1)) 

df_scaled = min_max_scaler.fit_transform(df)

df_normalized = df.copy()
df_normalized = pd.DataFrame(df_scaled)


In [47]:

df.to_pickle(basePath + dataset + "_normalized.pickle")

In [48]:
# Reshaping each row of the DataFrame to 5*5 matrix
data_dim = 9
ar = np.array(df_normalized.values.tolist())
ar = ar.reshape(ar.shape[0] ,data_dim , -1)


In [49]:
ar.shape

(34465, 9, 9)

In [50]:
# Saving reshaped data to be loaded later
import pickle

with open(basePath + dataset + ".pickle", 'wb') as handle:
    pickle.dump(ar , handle, protocol=pickle.HIGHEST_PROTOCOL)
    

In [13]:
# Finding Average value of candidate column for labeling the data

col =   'Total Payments'             
print (max(df[col]) , min(df[col]) , df[col].median() , df[col].mean() , len(df[col] > 5500))

x = np.array([500930.73999999999 ,-30728.27,54959.080000000002 , 63014.632040153258 
               ])
x= x.reshape(-1, 1)
ds =min_max_scaler.fit_transform(x)
ds

500930.74 -30728.27 54959.08 63014.63204015281 285008


array([[ 1.        ],
       [-1.        ],
       [-0.6776605 ],
       [-0.64735705]])

In [22]:
# Adding a new collumn as label of each record. Will be used for training 
# -0.64 is the normalized value of the mean of column 9

label = np.array([ 1. if x > -0.64 else 0. for x in df_normalized[10]])

In [23]:
from scipy.stats import itemfreq

itemfreq(label)

array([[  0.00000000e+00,   1.62690000e+05],
       [  1.00000000e+00,   1.22318000e+05]])

In [190]:
# Saving normalized data with the lable as the last column in a pickle file

#label.to_pickle("data/y_train_" + dataset + ".pickle")

In [30]:
 
with open("data/y_train_" + dataset + ".pickle", 'wb') as handle2:
    pickle.dump(label, handle2, protocol=pickle.HIGHEST_PROTOCOL)
    
    

In [40]:
with open("data/y_train_" + dataset + ".pickle", 'rb') as handle:
    y = pickle.load(handle)

In [41]:
# Should be similar to saved one 
print( str( y.shape))
y[0:2] == label[0:2]

(285008,)


array([ True,  True], dtype=bool)

In [46]:
y = y.astype(np.int)
y_dim = 2
y_vec = np.zeros((len(y), y_dim), dtype=np.float)
print(y_vec.shape)
for i, l in enumerate(y):
    y_vec[i, y[i]] = 1.0

(285008, 2)


In [47]:
y_vec

array([[ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       ..., 
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]])

In [220]:
idx= 0
batch_size = 64
train_size =np.inf 
batch_idxs = min(len(df_loaded), train_size) // batch_size # config.batch_size
grayscale = True
print(batch_idxs)

4453


In [221]:
c = 0
for idx in range(0, batch_idxs):
    batch = df_loaded[idx *  batch_size : (idx + 1) * batch_size]

    batch_images = np.array(batch).astype(np.float32)
    c =c + 1

In [222]:
c , batch_images.shape , len(df_loaded)

(4453, (64, 5, 5), 285008)

In [224]:
idx  = 4453
batch = df_loaded[idx *  batch_size : (idx + 1) * batch_size]

batch_images = np.array(batch).astype(np.float32)

batch_images.shape

(16, 5, 5)